### ISSUE TITLE
example wont work

### ISSUE THREAD

**Issue by MauMaxxa** [oliveroneill/FeedCollectionViewController#1]
using pod install in example results in 

[!] Unable to find a specification for `ImageFeedCollectionViewController`

Thank You, 
Looks promising!!

**Comment by oliveroneill** [comment]
Hmm I'm unable to recreate this one. Are you sure `ImageFeedCollectionViewController.podspec` is still at the top level of the repo? It might be worth cloning into a fresh directory and trying again. The example project should only look in the base directory for that podspec.

**Comment by MauMaxxa** [comment]
Uhm thank you i fixed with an update of cocoapods..!

Thank you!
