### ISSUE TITLE
Single image browser with remote images

### ISSUE THREAD

**Issue by MauMaxxa** [oliveroneill/FeedCollectionViewController#3]
Hi man :) sorry for my noobness!!

How can i handle remote images with your work?
I'm trying to edit your example, and i did this:

```
let url = URL(string: imgSource)
        imgView?.kf.setImage(with: url, placeholder: nil, options: nil, progressBlock: nil, completionHandler: {
            (image, error, CacheType, imageUrl) in
            if let img=image {
                self.image = img
            }            
        })
```

Inside ColorImageCellData. The images are showing, but when i select one of them, i always see it empty..!

Thank you!

**Comment by oliveroneill** [comment]
In `ColorImageCellData` in the `init` function, you should call `super.init(url: url)` for the URL you generated from `imgSource` above. I'll document this more clearly.

**Comment by MauMaxxa** [comment]
Thanks man..!:)

It works
